name: GKI Kernel Module Build

on:
  workflow_dispatch:

    
jobs:
    build:
      name: GKI Kernel Module Build
      runs-on: ubuntu-22.04
      strategy:
        matrix:
          tag:
            - android12-5.10
            - android13-5.10
            - android13-5.15
            - android14-5.15
            - android14-6.1
            - android15-6.6
          arch:
            - aarch64
            - x86_64
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
  
        - name: Run GKI Kernel Build Action
          uses: feicong/android-kernel-build-action@main
          with:
            tag: ${{ matrix.tag }}
            arch: ${{ matrix.arch }}
