name: GKI Kernel Module Build

on:
  workflow_dispatch:

    
jobs:
    build:
      name: GKI Kernel Module Build
      runs-on: ubuntu-22.04
      strategy:
        matrix:
          tag:
            - android12-5.10
            - android13-5.10
            - android13-5.15
            - android14-5.15
            - android14-6.1
            - android15-6.6
            - android16-6.12
          arch:
            - aarch64
            - x86_64
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
  
        - name: Upload LKM Source Code
          uses: actions/upload-artifact@v4
          with:
            name: hello-ko-${{ matrix.tag }}-${{ matrix.arch }}
            path: .github/hello-ko

        - name: Run GKI Kernel Build Action
          uses: ./
          with:
            arch: ${{ matrix.arch }}
            tag: ${{ matrix.tag }}
            module-name: hello-ko
            module-path: hello-ko-${{ matrix.tag }}-${{ matrix.arch }}
